import re

from datetime import timedelta

from .types import ActionType, Logmails, OutputFormat, ContentType, JsonPath, OAuth2GrantType
from .yaml import HAS_YAML

__all__ = (
    '__version__',
    'DEFAULT_EMAIL_SENDER',
    'DEFAULT_EMAIL_HOST',
    'DEFAULT_ACTION',
    'DEFAULT_SUBJECT',
    'DEFAULT_BODY',
    'DEFAULT_WAIT_FILE_NOT_FOUND',
    'DEFAULT_WAIT_LINE_INCOMPLETE',
    'DEFAULT_WAIT_NO_ENTRIES',
    'DEFAULT_WAIT_BEFORE_SEND',
    'DEFAULT_WAIT_AFTER_CRASH',
    'DEFAULT_MAX_ENTRIES',
    'DEFAULT_MAX_EMAILS_PER_MINUTE',
    'DEFAULT_MAX_EMAILS_PER_HOUR',
    'DEFAULT_MAX_ENTRY_LINES',
    'DEFAULT_LOG_FORMAT',
    'DEFAULT_LOG_DATEFMT',
    'DEFAULT_LOGMAILS',
    'DEFAULT_OUTPUT_INDENT',
    'DEFAULT_OUTPUT_FORMAT',
    'DEFAULT_ENTRY_START_PATTERN',
    'DEFAULT_WARNING_PATTERN',
    'DEFAULT_ERROR_PATTERN',
    'DEFAULT_HTTP_METHOD',
    'DEFAULT_HTTP_MAX_REDIRECT',
    'DEFAULT_HTTP_PARAMS',
    'DEFAULT_HTTP_CONTENT_TYPE',
    'DEFAULT_OAUTH2_GRANT_TYPE',
    'DEFAULT_OAUTH2_REFRESH_MARGIN',
    'DEFAULT_FILE_MODE',
    'DEFAULT_JSON_BRIEF',
    'ROOT_CONFIG_PATH',
)

__version__ = '0.7.0'

DEFAULT_EMAIL_SENDER = 'logmon'
DEFAULT_EMAIL_HOST = 'localhost'
DEFAULT_ACTION: ActionType = 'SMTP'

DEFAULT_SUBJECT = '{brief}'
DEFAULT_BODY = '{logfile}\n\n{entries_str}'
DEFAULT_WAIT_FILE_NOT_FOUND = 30
DEFAULT_WAIT_LINE_INCOMPLETE = 0.1
DEFAULT_WAIT_NO_ENTRIES = 5
DEFAULT_WAIT_BEFORE_SEND = 1
DEFAULT_WAIT_AFTER_CRASH = 10
DEFAULT_MAX_ENTRIES = 20
DEFAULT_MAX_EMAILS_PER_MINUTE = 6
DEFAULT_MAX_EMAILS_PER_HOUR = 60
DEFAULT_MAX_ENTRY_LINES = 2048
DEFAULT_LOG_FORMAT = '[%(asctime)s] [%(process)d] %(levelname)s: %(message)s'
DEFAULT_LOG_DATEFMT = '%Y-%m-%dT%H:%M:%S%z'
DEFAULT_LOGMAILS: Logmails = 'onerror'

DEFAULT_OUTPUT_INDENT = 4
DEFAULT_OUTPUT_FORMAT: OutputFormat = 'YAML' if HAS_YAML else 'JSON'

DEFAULT_ENTRY_START_PATTERN = re.compile(r'^\[\d\d\d\d-\d\d-\d\d[T ]\d\d:\d\d:\d\d(?:\.\d+)?(?: ?(?:[-+]\d\d:?\d\d|Z))?\]', re.I)
DEFAULT_WARNING_PATTERN = re.compile(r'WARNING', re.I)
DEFAULT_ERROR_PATTERN = re.compile(r'ERROR|CRITICAL|Exception', re.I)

DEFAULT_HTTP_METHOD = 'POST'
DEFAULT_HTTP_MAX_REDIRECT = 0
DEFAULT_HTTP_PARAMS: list[tuple[str, str]] = [
    ('subject', '{subject}'),
    ('receivers', '{receivers}'),
    ('entries', '{entries_raw}'),
]
DEFAULT_HTTP_CONTENT_TYPE: ContentType = 'URL'
DEFAULT_OAUTH2_GRANT_TYPE: OAuth2GrantType = 'client_credentials'
DEFAULT_OAUTH2_REFRESH_MARGIN = timedelta(seconds=30)

DEFAULT_FILE_MODE = 0o664

DEFAULT_JSON_BRIEF: JsonPath = ['message']

ROOT_CONFIG_PATH = '/etc/logmonrc'
